version: '2.4'

networks:
  {{DOCKER_NETWORK_NAME}}-peer:
    name: ${ENVIRONMENT:?ENVIRONMENT no encontrada}_${NETWORK_NAME:?NETWORK_NAME no encontrada}

services:
  {{NODE_NAME}}:
    mem_limit: 4g
    labels:
      app: padfed
    container_name: ${NODE_NAME:?NODE_NAME no encontrada}
    image: hyperledger/fabric-peer:${FABRIC_VERSION:?FABRIC_VERSION no encontrada}
    environment:
      - CORE_PEER_ID=${NODE_NAME}
      - CORE_PEER_ADDRESS=${NODE_NAME}:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${ENVIRONMENT}_${NETWORK_NAME}
      - CORE_PEER_LOCALMSPID=${MSPID:?MSPID no encontrada}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/node/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=${ENVIRONMENT}
      #LOGGING/PROFILING
      - FABRIC_LOGGING_SPEC=${LOG_LEVEL:?LOG_LEVEL no encontrada}
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      #- CORE_PEER_PROFILE_ENABLED=true

      # GOSSIP
      #- CORE_PEER_GOSSIP_ENDPOINT=${NODE_NAME}:${PEER_PORT:?PEER_PORT no encontrada}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${NODE_NAME}:${PEER_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${ANCHOR_PEER_NAME}:${PEER_PORT}
      #- CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_GOSSIP_ORGLEADER=false
      #- CORE_PEER_GOSSIP_SKIPHANDSHAKE=true

      # TLS
      - CORE_PEER_TLS_ENABLED=${TLS_ENABLED:?TLS_ENABLED no encontrada}
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/node/tls/peer-tls-server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/node/tls/peer-tls-server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/node/tls/ca.crt

      # TLS client auth
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=${TLS_CLIENT_AUTH_REQUIRED:?TLS_CLIENT_AUTH_REQUIRED no encontrada}
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/node/tls/peer-tls-client.key
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/node/tls/peer-tls-client.crt
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/node/tls/ca.crt

      # LEDGER
      - CORE_LEDGER_STATE_TOTALQUERYLIMIT=100000

      # OPERATIONS
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=:${OPERATIONS_PORT}
      - CORE_OPERATIONS_TLS_ENABLED=${OPERATIONS_ENABLE}
      - CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED=true
      - CORE_OPERATIONS_TLS_KEY_FILE=/etc/hyperledger/node/tls/peer-tls-server.key
      - CORE_OPERATIONS_TLS_CERT_FILE=/etc/hyperledger/node/tls/peer-tls-server.crt
      # Warning !!!
      # Para un orderer es ORDERER_OPERATIONS_TLS_CLIENTROOTCAS
      # Para un peer es    ORDERER_OPERATIONS_TLS_CLIENTROOTCAS_FILES
      - CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/node/operations/ca.crt

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - ${PEER_PORT}:7051
      - ${OPERATIONS_PORT}:${OPERATIONS_PORT}
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/etc/hyperledger/configtx
        - ./crypto-config:/etc/hyperledger/node
        - ${FABRIC_LEDGER_STORE_PATH:?FABRIC_LEDGER_STORE_PATH no encontrada}/${MSPID}-${NODE_BASENAME}:/var/hyperledger/production
    networks:
      - {{DOCKER_NETWORK_NAME}}-peer
#    extra_hosts:
#      - "orderer0.orderer.blockchain-tributaria.testnet.afip.gob.ar:0.0.0.0"
#      - "orderer1.:0.0.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  "{{NODE_NAME}}.cli":
    mem_limit: 1g
    labels: 
      app: padfed
    container_name: ${NODE_NAME}.cli
    image: hyperledger/fabric-tools:${FABRIC_VERSION}
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOG_LEVEL:?LOG_LEVEL key no encontrada}
      - CORE_PEER_ID=cli-${NODE_NAME}
      - CORE_PEER_ADDRESS=${NODE_NAME}:7051
      - CORE_PEER_LOCALMSPID=${MSPID}
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/admin/msp

      # TLS
      - CORE_PEER_TLS_ENABLED=${TLS_ENABLED}
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/node/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/node/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/node/tls/ca.crt

      # TLS client auth
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=${TLS_CLIENT_AUTH_REQUIRED}
      - CORE_PEER_TLS_CLIENTKEY_FILE=/etc/hyperledger/admin/tls/client.key
      - CORE_PEER_TLS_CLIENTCERT_FILE=/etc/hyperledger/admin/tls/client.crt
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/etc/hyperledger/admin/tls/ca.crt

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run:/host/var/run/
      - ./crypto-config:/etc/hyperledger/configtx
      - ./crypto-config/msp:/etc/hyperledger/node/msp
      - ./crypto-config/tls:/etc/hyperledger/node/tls
      - ./crypto-config/admin/msp:/etc/hyperledger/admin/msp
      - ./crypto-config/admin/tls:/etc/hyperledger/admin/tls
      - ./crypto-config/orderer/tls:/etc/hyperledger/orderer/tls
      - ./gopath:/opt/gopath/
    networks:
      - {{DOCKER_NETWORK_NAME}}-peer
    depends_on:
      - ${NODE_NAME}
#   extra_hosts:
#     - "orderer0.orderer.blockchain-tributaria.testnet.afip.gob.ar:0.0.0.0"
#     - "orderer1.:0.0.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
