NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.morgs.blockchain-tributaria.testnet.afip.gob.ar-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
  #   Certificate: x
    OrganizationalUnitIdentifier: x
