Organizations:
    - &ORDERER
        Name: ORDERER
        ID: ORDERER
        MSPDir: crypto-config/ordererOrganizations/{{ORDERER_DOMAIN_NAME}}.{{ENVIRONMENT}}.{{ORDERER_NETWORK_DOMAIN_NAME}}/msp

    - &AFIP
        Name: AFIP
        ID: AFIP
        MSPDir: crypto-config/peerOrganizations/{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.afip.{{ORGS_NETWORK_DOMAIN_NAME}}/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.afip.{{ORGS_NETWORK_DOMAIN_NAME}}
              Port: 7051

    - &COMARB
        Name: COMARB
        ID: COMARB
        MSPDir: crypto-config/peerOrganizations/{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.comarb.{{ORGS_NETWORK_DOMAIN_NAME}}/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.comarb.{{ORGS_NETWORK_DOMAIN_NAME}}
              Port: 7051

    - &ARBA
        Name: ARBA
        ID: ARBA
        MSPDir: crypto-config/peerOrganizations/{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.arba.{{ORGS_NETWORK_DOMAIN_NAME}}/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.{{BLOCKCHAIN_NETWORK_NAME}}.{{ENVIRONMENT}}.arba.{{ORGS_NETWORK_DOMAIN_NAME}}
              Port: 7051


################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
      # V1.3 for Channel is a catchall flag for behavior which has been
      # determined to be desired for all orderers and peers running at the v1.3.x
      # level, but which would be incompatible with orderers and peers from
      # prior releases.
      # Prior to enabling V1.3 channel capabilities, ensure that all
      # orderers and peers on a channel are at v1.3.0 or later.
      V1_3: true
      # V1.2 for Global is a catchall flag for behavior which has been
      # determined to be desired for all orderers and peers running v2.0.x,
      # but the modification of which would cause incompatibilities.  Users
      # should leave this flag set to true.
      V1_2: false
      # V1.1 for Global is a catchall flag for behavior which has been
      # determined to be desired for all orderers and peers running v1.0.x,
      # but the modification of which would cause incompatibilities.  Users
      # should leave this flag set to true.
      V1_1: false

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
      # V1.1 for Order is a catchall flag for behavior which has been
      # determined to be desired for all orderers running v1.0.x, but the
      # modification of which  would cause incompatibilities.  Users should
      # leave this flag set to true.
      V1_1: true

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
      # V1.3 for Application enables the new non-backwards compatible
      # features and fixes of fabric v1.3.
      V1_3: true
      # V1.2 for Application enables the new non-backwards compatible
      # features and fixes of fabric v1.2 (note, this need not be set if
      # later version capabilities are set)
      V1_2: false
      # V1.1 for Application enables the new non-backwards compatible
      # features and fixes of fabric v1.1 (note, this need not be set if
      # later version capabilities are set).
      V1_1: false

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - {{ORDERER_HOSTNAME}}.{{ORDERER_DOMAIN_NAME}}.{{ENVIRONMENT}}.{{ORDERER_NETWORK_DOMAIN_NAME}}:{{ORDERER_PORT}}

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 1000

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 5 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 4096 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    SetupGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *ORDERER
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            Consortium:
                Organizations:
                    - *AFIP
                    - *COMARB
                    - *ARBA
    SetupChannel:
        Consortium: Consortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *AFIP
                - *COMARB
                - *ARBA
            Capabilities:
                <<: *ApplicationCapabilities

